apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace

  params:
    - name: repo-url
    - name: branch
      default: main

  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: clone
      runAfter:
        - cleanup
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)

    - name: lint
      runAfter:
        - clone
      taskRef:
        name: flake8
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: test
      runAfter:
        - lint
      taskRef:
        name: nosetests
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: build
      runAfter:
        - test
      taskRef:
        name: buildah

    - name: deploy
      runAfter:
        - build
      taskRef:
        name: kubectl